schema_version: 20180708
name: dukes-birthday-function
version: 0.0.1
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.85
run_image: fnproject/fn-java-fdk:jdk9-1.0.85
cmd: eu.agilejava.BirthdayFunction::handleRequest
format: http-stream
triggers:
- name: dukes-birthday-function-trigger
  type: http
  source: /dukes-birthday-function-trigger
