schema_version: 20180708
name: dukes-birthday-function
version: 0.0.26
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: eu.agilejava.BirthdayFunction::handleRequest
triggers:
- name: birthday
  type: http
  source: /birthday
